version: '3'

services:
  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "bitcoindb"
    ports:
      - "3306:3306"
    volumes:
      - /home/fernando/docker-databases/mysql:/var/lib/mysql3
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
